Feature/soo step1
C4-ComeTrue/c4-cometrue-assignment pull request #2
Opened 2024-01-29 15:33 UTC by youngsoosoo

## ERD
![image](https://github.com/C4-ComeTrue/c4-cometrue-assignment/assets/87405853/5f0ddf33-87b4-4039-a72f-dcd52bd0337c)

## 회원 가입 및 인증
사용자 정보는 평범하게 구현했습니다.

- 로그인: 로그인 시 회원의 Email 정보가 담긴 JWT 토큰을 반환하도록 진행
- 회원가입: 회원가입 시 회원의 계좌를 생성해주기 위해 이벤트 리스너 등록

#### 개선점
- 로그인 시 하나의 JWT 토큰이 아닌 RefreshToken, AccessToken으로 나누어 보안성을 높이는 것이 좋을 거 같습니다.

## 계좌
- 계좌 Type: Enum을 통해 계좌의 형태를 나타내주었습니다.
- 1일 충전 한도: 관계형 데이터베이스에 컬럼을 추가해 관리할 수 있도록 만들었습니다.
- 계좌 간 거래: 특정 엔티티(행)에 대한 동시성 제어를 위해 비관적 락 사용, 메인 계좌에 잔액이 부족할 시 에러 처리
  - 트랜잭션 격리 수준 중 SERIALIZABLE을 사용하면 데드락이 발생할 수 있습니다. 그래서 락을 통해 동시성 제어를 해주었습니다.

#### 개선점
- 현재는 1일 충전 한도를 관계형 데이터 베이스에 저장하고 있습니다. 이후에 Redis의 TTL(Time To Live) 이라는 기능을 통해 관리해주면 좋을 거 같습니다.

2024-02-05 18:35 UTC, VSFe requested changes
수고했습니다~
간단하게 코멘트 달아 드렸습니다.

2024-02-05 18:35 UTC, VSFe commented on build.gradle
> +    implementation 'junit:junit:4.13.1'
Junit 4 보다는 5를 사용하면 좋을 것 같아요.
(spring-boot-starter-test 에는 기본적으로 Junit 5가 내장되어 있습니다.)

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/controller/AccountController.java
> +        @Valid
Parameter의 Annotation은 Parameter 하나당 one-line으로 작성해 주세요.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/dto/RequestDto.java
> +        @NotBlank
`@NotBlank` 는 charSequence에 적용하는 Validation Annotation 입니다.
전체적으로 잘못 적용된 것 같네요.

https://github.com/hibernate/hibernate-validator/blob/main/engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/NotBlankValidator.java

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/dto/ResponseDto.java
> +        Long id,
Validation을 쓸거면, 다 넣는게 맞겠죠?

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/dto/RequestDto.java
> +public class RequestDto {
굳이 RequestDto, ResponseDto로 묶을 필요가 있나 싶어요.
Record의 Style이 깨지는 느낌이 강하게 듭니다.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/entity/Account.java
> +    private Integer balance;
int의 range는 2,147,483,647 인데, 현실적인 시나리오를 고려하면 21억을 넘는 경우도 충분히 있을 것 같네요.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/repository/AccountRepository.java
> +    @Query("SELECT a FROM Account a "
JDK 15부터, MuitiLineString이 가능합니다.

```java
@Query("""SELECT a FROM Account a
WHERE a.member.id = :memberId
AND a.id = :id
""")
```

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +@Log4j2
logger를 사용하지 않는데 `@Log4j2`를 다셨어요.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +        if (dailyLimit > 3000000) {
일반적으로 literal 값은 static final 변수로 고정하는 것이 권장됩니다.
```java
public static final int DAILY_LIMIY = 3_000_000;
```

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +        Account account = accountRepository.findByAccount(member.getId(), rechargeAccountDto.accountId());
`accountRepository.findByAccount()`는 nullable 하네요.
(member가 존재한다고 account가 반드시 존재하나요? 100% 성공된다는 보장이 있진 않으니, 체크하는 로직을 추가하거나 `saveAccount()` 가 실패한다고 해도 어떻게든 계좌를 만들 수 있는 방법을 생각해 보세요.)

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +        String memberEmail = JwtTokenUtil.getMemberEmail(token, secretKey);
사실상 거의 모든 로직에 회원 정보를 조회해서 멤버 객체로 뱉는 프로세스가 포함되어 있네요.
반복된 코드를 제거할 수 없을까요?

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +    // 없는 계좌는 조회가 안 되기에 예외 처리 x
조회가 안 된다고 repository 단에서 예외를 뱉지 않습니다. (애초에 일반적으로 검색 결과가 없는 것에 대한 예외는 Service 레이어에서 많이 처리하고요.)
현재 로직이라면, 둘 중 하나에 null이 나올 시 NPE가 발생하겠네요.
NPE는 Internal Server Error로 취급되므로, 실 서비스에서 발생하면 안 되는 예외입니다.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/auth/config/SecurityConfig.java
> +                    config.setAllowedOrigins(List.of("http://localhost:3000", "http://localhost:80"));
CORS 완전 해제는 Local Profile에 한 해 enable 시키거나, 제거하는게 낫겠네요.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/auth/jwt/JwtTokenFilter.java
> +        Member loginUser = memberService.getMemberByEmail(loginEmail);
filter가 Service를 바라보는건 좋아보이지 않네요.
의도하지 않은 결과가 나올 것 같습니다.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/auth/service/CustomUserDetailService.java
> +@Slf4j
한 쪽에서는 `@Slf4j`를, 한 쪽에서는 `@Log4j`를 사용하고 있네요.
로깅 시스템에 대해 조사해 보세요.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/auth/service/CustomUserDetailService.java
> +        return new org.springframework.security.core.userdetails.User(
??

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/member/dto/RequestDto.java
> +            regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$",
`@Email` 로 변경해 주세요.

2024-02-05 18:35 UTC, VSFe commented on src/main/resources/application-prod.yml
> +    password: 4015pskc
prod 환경에서 비밀번호를 관리할 방법을 생각해 보세요.

2024-02-05 18:35 UTC, VSFe commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
무슨일이 있어도, 절대, 절대, 절대 prod 환경에서 update/create/drop 등을 사용하면 안 됩니다.

2024-02-05 18:35 UTC, VSFe commented on src/main/resources/application.yml
> +  datasource:
다른 application.yml 에도 있는 중복된 설정값이네요.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/util/entity/BaseEntity.java
> +        status = Status.ACTIVE;
이후에 추가되는 모든 entity에 status가 있음이 보장되나요?

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/member/service/MemberService.java
> +            throw new BaseException(ErrorCode.LOGIN_FAILED.toString(), HttpStatus.EXPECTATION_FAILED.toString());
잘못된 HttpStaus를 사용하고 있습니다.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/member/service/MemberService.java
> +        log.info("join: " + joinDto.email());
logger의 문자열은 다음과 같은 방식으로 작성해 주세요.
`log.info("join: {}", joinDto.email());`

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/auth/jwt/JwtTokenUtil.java
> +        claims.put("memberEmail", memberEmail);
반복되는 literal은 분리해 주세요.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/auth/jwt/JwtTokenFilter.java
> +    private final String secretKey;
secretKey를 잘 들고 오나요?

2024-02-05 18:35 UTC, VSFe commented on src/test/java/org/c4marathon/assignment/account/controller/AccoutControllerTest.java
> +public class AccoutControllerTest {
현재, CI 환경에서 테스트 코드가 작동하지 않습니다.
확인해 주세요.

2024-02-05 18:35 UTC, VSFe commented on src/test/java/org/c4marathon/assignment/AssignmentApplicationTests.java
>  class AssignmentApplicationTests {
없어도 되겠네요.

2024-02-05 18:35 UTC, VSFe commented on src/main/java/org/c4marathon/assignment/account/repository/AccountRepository.java
> +    @Query("SELECT a FROM Account a "
member_id로 인덱스가 필요하겠네요.

2024-02-06 05:23 UTC, seungh1024 commented on src/test/java/org/c4marathon/assignment/AssignmentApplicationTests.java
>  class AssignmentApplicationTests {
여기 때문에 CI 환경에서 테스트 코드가 깨질 겁니다. 저도 그랬거든요..

2024-02-06 14:30 UTC, youngsoosoo commented on src/test/java/org/c4marathon/assignment/AssignmentApplicationTests.java
>  class AssignmentApplicationTests {
아 감사합니다. 이 부분 해결하느라 찾다가....
승훈님 코드 보면서 공부 좀 해야겠네요,,

2024-02-06 15:45 UTC, seungh1024 commented on src/test/java/org/c4marathon/assignment/AssignmentApplicationTests.java
>  class AssignmentApplicationTests {
제 코드에 특별한 해결 방법이 있는건 아니라서 @SpringBootTest가 어떻게 동작하는지 살펴보면 왜 CI 환경에서 안됐는지 알 수 있을겁니당

2024-02-07 08:19 UTC, youngsoosoo commented on build.gradle
> +    implementation 'junit:junit:4.13.1'
넵.

2024-02-07 08:19 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/controller/AccountController.java
> +        @Valid
넵.

2024-02-07 10:44 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/dto/RequestDto.java
> +public class RequestDto {
RequestDto나 ResponseDto로 묶어서 사용하게 되면, 이들이 하나의 큰 묶음으로 작동하게 되고, 각각의 필드가 독립적인 의미를 가지기 어렵군요...
감사합니다!

2024-02-07 10:51 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/dto/RequestDto.java
> +        @NotBlank
말씀해주신대로 @NotBlank 어노테이션은 CharSequence에 적용되는 검증 어노테이션이며, String 타입의 필드에 주로 사용됩니다. @NotNull 어노테이션으로 수정하여 해당 필드가 null이 아님을 검증하도록 하겠습니다.

2024-02-07 11:09 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/dto/ResponseDto.java
> +        Long id,
응답 객체에도 유효성 검사를 진행해주나요??

2024-02-07 11:22 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/entity/Account.java
> +    private Integer balance;
말씀해주신 대로 int의 range는 2,147,483,647입니다.
그래서 더 큰 범위(-9,223,372,036,854,775,808~9,223,372,036,854,775,807)인 Long 타입으로 변경하겠습니다.

2024-02-07 11:43 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/repository/AccountRepository.java
> +    @Query("SELECT a FROM Account a "
오 이런 게 있었군요...
MuitiLineString 형태로 수정하니 가독성이 더 좋아진 거 같습니다.

2024-02-07 11:46 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +@Log4j2
넵 수정하겠습니다.

2024-02-08 02:11 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +        if (dailyLimit > 3000000) {
Java에서 숫자에 _를 사용할 수 있군요..
literal 값은 static final 변수로 고정하여 사용하겠습니다.

2024-02-08 07:29 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/auth/jwt/JwtTokenFilter.java
> +    private final String secretKey;
넵.
Spring Security에서 HTTP 요청이 들어올 때마다 JwtTokenFilter를 필터 체인에 등록하고, addFilterBefore() 메소드를 통해 JwtTokenFilter 인스턴스를 생성할 때 memberService와 secretKey를 전달해줍니다.

2024-02-14 09:08 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/auth/jwt/JwtTokenFilter.java
> +        Member loginUser = memberService.getMemberByEmail(loginEmail);
필터는 HTTP 요청을 처리하는 단계에서 사용되는데, 비즈니스 로직이 포함되면서 단일 책임 원칙에 위반될 뿐만 아니라 현재 로직에서 불필요한 거 같아서 제거했습니다.

2024-02-14 09:30 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/auth/service/CustomUserDetailService.java
> +        return new org.springframework.security.core.userdetails.User(
데이터를 올바르게 가져오나 확인할 때 사용했던 로그가 그대로 남아있었습니다. 불필요하니 제거하겠습니다.

2024-02-14 10:22 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +        String memberEmail = JwtTokenUtil.getMemberEmail(token, secretKey);
Security에서 addFilterBefore를 통해 AUTHORIZATION 헤더에 담긴 토큰에 대한 검증을 진행하도록 변경했습니다. 또한 AccountService에서 멤버 객체를 반환하는 private 메서드를 통해 반복된 코드를 제거했습니다.

2024-02-15 16:51 UTC, youngsoosoo commented on src/main/resources/application.yml
> +  datasource:
넵.
제거했습니다.

2024-02-15 17:23 UTC, youngsoosoo commented on src/test/java/org/c4marathon/assignment/AssignmentApplicationTests.java
>  class AssignmentApplicationTests {
감사합니다. 이 부분 해결했습니다.

2024-02-15 17:23 UTC, youngsoosoo commented on src/test/java/org/c4marathon/assignment/account/controller/AccoutControllerTest.java
> +public class AccoutControllerTest {
testImplementation 'com.h2database:h2' 의존성으로 변경해 CI 환경에서 테스트가 작동하도록 수정했습니다.

2024-02-17 16:44 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +    // 없는 계좌는 조회가 안 되기에 예외 처리 x
클라이언트에서 계좌 전체 조회할 때 존재하지 않는 계좌는 요청이 들어올 일이 없다고 생각해 코드를 작성했습니다.
하지만 혹시 null이 나올 상황을 대비하여 Optionals의 orElseThrow를 사용하여 예외 처리를 해주었습니다.

2024-02-17 17:07 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/service/AccountService.java
> +        Account account = accountRepository.findByAccount(member.getId(), rechargeAccountDto.accountId());
만약 회원가입 시 등록한 이벤트가 실패한다면 메인 계좌가 생성되지 않습니다.
이를 orElseGet을 사용하여 생성 요청 후 조회할 수 있도록 예외 처리를 해주었습니다.

2024-02-17 17:11 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/auth/service/CustomUserDetailService.java
> +@Slf4j
일단은 사용하지 않아 제거해주었습니다.

로깅 시스템은 소프트웨어가 실행되는 동안 발생하는 이벤트를 기록하고 관리하는 시스템입니다.
차이점으로는 @Slf4j는 다양한 로깅 시스템에 대한 통일된 인터페이스를 제공하는 장점이 있으며, @Log4j는 성능과 유연성이 뛰어나다는 장점이 있습니다.

2024-02-17 17:12 UTC, youngsoosoo commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
넵.
현재는 ddl-auto: none로 변경해주었습니다.

2024-02-17 17:16 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/member/service/MemberService.java
> +            throw new BaseException(ErrorCode.LOGIN_FAILED.toString(), HttpStatus.EXPECTATION_FAILED.toString());
401 Unauthorized로 수정해주었습니다.

2024-02-17 17:17 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/member/service/MemberService.java
> +        log.info("join: " + joinDto.email());
넵 로그 남길 때 참고하겠습니다.
현재는 불필요해서 제거해 주었습니다.

2024-02-17 17:31 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/auth/config/SecurityConfig.java
> +                    config.setAllowedOrigins(List.of("http://localhost:3000", "http://localhost:80"));
수정해주었습니다.

2024-02-17 17:34 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/auth/jwt/JwtTokenUtil.java
> +        claims.put("memberEmail", memberEmail);
넵.

2024-02-17 17:35 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/member/dto/RequestDto.java
> +            regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$",
넵 수정했습니다.

2024-02-17 17:41 UTC, youngsoosoo commented on src/main/resources/application-prod.yml
> +    password: 4015pskc
보통 서브 모듈을 이용한 방법이나 환경변수로 설정하여 사용하는 방법이 주로 사용되는데, 환경 변수 등록은 제가 할 수 없으니 서브 모듈을 이용한 방법으로 후에 수정하겠습니다.

2024-02-17 17:45 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/util/entity/BaseEntity.java
> +        status = Status.ACTIVE;
이후에 진행되는 송금 받기 기능과 송금 내역 관리를 한 테이블(PayHistory)을 사용해 진행하려고 했습니다.
이렇게 되면 3개의 테이블로 회원, 계좌, 관리 모두 status가 모든 Entity에 포함되도록 생각했는데, 혹시 안 좋은 방법이거나 더 좋은 방법이 있다면 피드백 부탁드리겠습니다.

2024-02-18 09:01 UTC, youngsoosoo commented on src/main/java/org/c4marathon/assignment/account/repository/AccountRepository.java
> +    @Query("SELECT a FROM Account a "
Account Entity에 member_id로 인덱스를 설정해주었습니다.
Account 테이블은 member_id를 통한 조회를 많이 해주기 때문에 인덱스를 생성하는 것이 유리할 것이라는 생각이 듭니다.

추가적으로 인덱스에 대해 학습하겠습니다,

2024-02-26 12:20 UTC, merged